// packages/frameworks/react/src/renderer/GenuiRenderer.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ComponentType,
} from 'react';
import { DeltaPatcher, repairJson, RepairJsonState } from '@opentiny/genui-sdk-core';
import { SchemaRenderer, RendererContextProvider } from '@opentiny/tiny-schema-renderer-react';
import type { SchemaRendererHandle, SchemaRendererProps } from '@opentiny/tiny-schema-renderer-react';
import type { InstanceMaterials } from '@opentiny/tiny-schema-renderer-react';
import { useGenuiMaterials, useGenuiNotify } from '../config-provider';
import { requiredCompleteFieldSelectors as defaultSelectors } from './config';
import type { IRendererProps } from './renderer.types';
import './renderer.css';

type RootNode = NonNullable<SchemaRendererProps['schema']>;

const errorSchema: RootNode = {
  componentName: 'Page',
  children: [
    {
      componentName: 'Text',
      props: { text: 'Schema rendering error', style: 'line-height: 40px; color: #c00' },
    },
  ],
};

const emptySchema: RootNode = { componentName: 'Page' };

export const GenuiRenderer = forwardRef<SchemaRendererHandle, IRendererProps>(
  function GenuiRenderer(props, ref) {
    const contextMaterials = useGenuiMaterials();
    const notify = useGenuiNotify();
    const mergedComponents = useMemo(
      () => ({
        ...(contextMaterials.components as Record<string, ComponentType<any>> | undefined),
        ...props.customComponents,
      }),
      [contextMaterials.components, props.customComponents],
    );
    const renderSettings = useMemo(
      () => ({
        materials: {
          ...contextMaterials,
          components: mergedComponents,
        } as InstanceMaterials,
        notify,
      }),
      [contextMaterials, mergedComponents, notify],
    );
    const rendererRef = useRef<SchemaRendererHandle | null>(null);

    const updateContextAndState = useCallback(() => {
      const instance = rendererRef.current;
      if (!instance) return;

      instance.setContext({
        callAction: (actionName: string, params?: unknown) => {
          if (!props.customActions?.[actionName]) {
            console.warn(`Action ${actionName} not found`);
            return;
          }
          return props.customActions[actionName].execute(params, instance.getContext());
        },
      });
      if (props.id) {
        instance.setContext({ cardId: props.id });
      }
      instance.setState(props.state || {});
    }, [props.customActions, props.id, props.state]);

    const setRendererRef = useCallback(
      (instance: SchemaRendererHandle | null) => {
        rendererRef.current = instance;
        if (typeof ref === 'function') {
          ref(instance);
        } else if (ref) {
          ref.current = instance;
        }
      },
      [ref],
    );

    useEffect(() => {
      updateContextAndState();
    }, [updateContextAndState]);

    const schemaRef = useRef<RootNode>({ ...emptySchema });
    const [displaySchema, setDisplaySchema] = useState<RootNode>(schemaRef.current);
    const [isError, setIsError] = useState(false);
    const patcherRef = useRef<DeltaPatcher | null>(null);
    patcherRef.current = useMemo(
      () =>
        new DeltaPatcher({
          requiredCompleteFieldSelectors: [
            ...defaultSelectors,
            ...(contextMaterials.requiredCompleteFieldSelectors || []),
            ...(props.requiredCompleteFieldSelectors || []),
          ],
        }),
      [contextMaterials.requiredCompleteFieldSelectors, props.requiredCompleteFieldSelectors],
    );

    const contentKeyRef = useRef('');
    useEffect(() => {
      setIsError(false);
      let json: Record<string, unknown> = {};
      let isCompleted = true;
      const raw = props.content;

      if (typeof raw === 'string') {
        if (raw.trim()) {
          const { value, state } = repairJson(raw);
          if (!value || typeof value !== 'object') {
            setIsError(true);
            return;
          }
          json = value as Record<string, unknown>;
          isCompleted = state === RepairJsonState.SUCCESS;
        }
      } else {
        json = (raw as Record<string, unknown>) || {};
        isCompleted = props.generating ? false : (props.isJsonComplete ?? true);
      }

      if (!isCompleted && json && 'lifeCycles' in json) {
        const { lifeCycles: _, ...rest } = json;
        json = rest;
      }

      const nextKey = JSON.stringify(json) + String(isCompleted);
      if (!props.generating && contentKeyRef.current === nextKey) return;
      contentKeyRef.current = nextKey;

      patcherRef.current?.patchWithDelta(schemaRef.current, json, isCompleted);
      setDisplaySchema({ ...schemaRef.current });
    }, [props.content, props.isJsonComplete, props.generating]);

    useEffect(() => {
      updateContextAndState();
    }, [displaySchema, updateContextAndState]);

    return (
      <RendererContextProvider renderSettings={renderSettings}>
        <div className="genui-renderer-container schema-render-container">
          <SchemaRenderer
            ref={setRendererRef}
            schema={isError ? errorSchema : displaySchema}
          />
        </div>
      </RendererContextProvider>
    );
  },
);

// packages/frameworks/vue/src/renderer/GenuiRenderer.vue
<script setup lang="ts">
import { ref, watch, computed, inject, nextTick, onErrorCaptured, provide, shallowRef } from 'vue';
// @ts-ignore
import SchemaRenderer, { RENDERER_SETTINGS_KEY } from '@opentiny/tiny-schema-renderer';
import { DeltaPatcher, repairJson, RepairJsonState, type IMaterials } from '@opentiny/genui-sdk-core';
import { requiredCompleteFieldSelectors as internalRequiredCompleteFieldSelectors } from './config';
import { GENUI_MATERIALS } from '../config-provider/injection-tokens';
import type { IRendererProps } from './renderer.types';
import { cardIdSymbol } from '../chat/useChat';
import { useI18n } from '../chat/i18n';

onErrorCaptured((error) => {
  console.error('GenuiRenderer error:', error);
  return true;
});

const props = withDefaults(defineProps<IRendererProps>(), {
  isJsonComplete: true,
});

const schema = ref<any>({});
const rendererInstance = ref<SchemaRenderer | null>(null);

const callAction = (actionName: string, params: any) => {
  if (!props.customActions?.[actionName]) {
    console.warn(`Action ${actionName} not found`);
    return;
  }
  return props.customActions[actionName]?.execute(params, rendererInstance.value.getContext());
};

const materials = inject<IMaterials>(GENUI_MATERIALS, {});
const customSettings = inject(RENDERER_SETTINGS_KEY, {}) as Record<string, any>;

watch(() => props.customComponents, (newVal) => {
  // TODO:  1、materials.components更新后，customComponents会丢失 2、旧的customComponents没有被移除
  if (materials.components) {
    Object.assign(materials.components, newVal);
  }
}, { immediate: true });

customSettings.materials = materials;
provide(RENDERER_SETTINGS_KEY, customSettings);

const deltaPatcher = shallowRef(null);

watch(
  () => [materials?.requiredCompleteFieldSelectors, props.requiredCompleteFieldSelectors],
  () => {
    deltaPatcher.value = new DeltaPatcher({
      requiredCompleteFieldSelectors: [
        ...internalRequiredCompleteFieldSelectors,
        ...(materials?.requiredCompleteFieldSelectors || []),
        ...(props.requiredCompleteFieldSelectors || []),
      ],
    });
  },
  { immediate: true },
);

const { t } = useI18n();

const errorSchema = {
  componentName: 'Page',
  children: [
    {
      componentName: 'Text',
      props: {
        text: t('renderer.error.displayError'),
        style: 'line-height: 40px; color: var(--tv-color-error-text)',
      },
    },
  ],
};

const isError = ref(false);

const displaySchema = computed(() => {
  if (isError.value) {
    return errorSchema;
  }
  return schema.value;
});

let updateActionTimer: any | null = null;

function updateContextAndState() {
  rendererInstance.value?.setContext({
    callAction,
  });
  rendererInstance.value?.setContext({
    [cardIdSymbol]: props.id,
  });
  rendererInstance.value?.setState(props.state || {});
}

watch(
  [() => props.content, () => props.isJsonComplete],
  ([newVal, isJsonComplete]) => {
    isError.value = false;
    let json: any = newVal;
    let isCompleted = true;
    if (typeof newVal === 'string') {
      if (newVal.trim()) {
        const { value, state } = repairJson(newVal);
        if (!value || typeof value !== 'object') {
          isError.value = true;
          return;
        }
        json = value;
        isCompleted = state === RepairJsonState.SUCCESS;
      } else {
        json = {};
      }
    } else {
      isCompleted = isJsonComplete ?? true;
    }
    if (!isCompleted && json && 'lifeCycles' in json) {
      const { lifeCycles, ...rest } = json;
      json = rest;
    }
    deltaPatcher.value.patchWithDelta(schema.value, json, isCompleted); // TODO： 速率限制
    if (!updateActionTimer) {
      updateActionTimer = nextTick(() => {
        if (!rendererInstance.value) return;
        updateContextAndState();
        updateActionTimer = null;
      });
    }
  },
  {
    immediate: true,
  },
);
// 异步组件可能在更新context时候并未ready，导致恢复会话的时候context没更新
watch(
  () => rendererInstance.value,
  (newVal) => {
    if (newVal && updateActionTimer) {
      nextTick(() => updateContextAndState());
      updateActionTimer = null;
    }
  },
  {
    immediate: true,
  },
);
</script>

<template>
  <div class="schema-render-container">
    <slot name="header" :schema="schema" :isError="isError" :isFinished="!props.generating"></slot>
    <SchemaRenderer :schema="displaySchema" ref="rendererInstance" />
    <slot name="footer" :schema="schema" :isError="isError" :isFinished="!props.generating"></slot>
  </div>
</template>

<style scoped>
@import url('./custom.css');

.schema-render-container {
  position: relative;
  color: var(--tv-color-text, #191919);
}

.schema-render-container:has(.loading-warp):after {
  display: none;
}

:deep(.loading-warp.loading-warp) {
  display: none;
}

:deep(.loading-warp .loading) {
  display: none;
}
</style>
