// docs/demos/en/react/renderer/state.tsx
import { GenuiConfigProvider, GenuiRenderer } from '@opentiny/genui-sdk-react';
import { materials } from '@opentiny/genui-sdk-materials-react-antd/materials';

const generating = false;

const content = {
  componentName: 'Page',
  state: {
    formData: {
      name: '',
      age: null,
    },
  },
  children: [
    {
      componentName: 'AntForm',
      props: {
        layout: 'vertical',
        style: { maxWidth: 480 },
      },
      children: [
        {
          componentName: 'AntFormItem',
          props: {
            label: 'Name',
          },
          children: [
            {
              componentName: 'AntInput',
              props: {
                placeholder: 'Enter your name',
                value: {
                  type: 'JSExpression',
                  value: 'this.state.formData.name',
                },
                onChange: {
                  type: 'JSFunction',
                  value: 'function(e) { this.state.formData.name = e.target.value; }',
                },
              },
            },
          ],
        },
        {
          componentName: 'AntFormItem',
          props: {
            label: 'Age',
          },
          children: [
            {
              componentName: 'AntInput',
              props: {
                placeholder: 'Enter your age',
                value: {
                  type: 'JSExpression',
                  value: 'this.state.formData.age',
                },
                onChange: {
                  type: 'JSFunction',
                  value: 'function(e) { this.state.formData.age = e.target.value; }',
                },
              },
            },
          ],
        },
        {
          componentName: 'AntFormItem',
          props: {},
          children: [
            {
              componentName: 'AntButton',
              props: {
                type: 'primary',
                onClick: {
                  type: 'JSFunction',
                  value: "function() { this.callAction('getState'); }",
                },
              },
              children: [
                {
                  componentName: 'Text',
                  props: {
                    text: 'View state',
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

const historyState = {
  formData: {
    name: 'John Doe',
    age: 30,
  },
};

const customActions = {
  getState: {
    execute: (_params: unknown, context: Record<string, unknown>) => {
      alert(`Restored state:\n${JSON.stringify(context.state, null, 2)}`);
    },
  },
};

export default function Demo() {
  return (
    <GenuiConfigProvider materials={materials}>
      <GenuiRenderer
        content={content}
        generating={generating}
        state={historyState}
        customActions={customActions}
        isJsonComplete
      />
    </GenuiConfigProvider>
  );
}

// docs/demos/en/renderer/state.vue
<template>
  <GenuiConfigProvider :materials="materials">
    <GenuiRenderer :content="content" :generating="generating" :state="historyState" :customActions="customActions" />
  </GenuiConfigProvider>
</template>

<script setup lang="ts">
import { materials } from '@opentiny/genui-sdk-materials-vue-opentiny-vue/materials';
import { ref } from 'vue';
import { GenuiConfigProvider, GenuiRenderer } from '@opentiny/genui-sdk-vue';

const generating = ref(false);

// Schema restored from history
const content = ref({
  componentName: 'Page',
  state: {
    formData: {
      name: '',
      age: null,
    },
  },
  children: [
    {
      componentName: 'TinyForm',
      props: {
        model: {
          type: 'JSExpression',
          value: 'this.state.formData',
        },
        'label-position': 'top',
      },
      children: [
        {
          componentName: 'TinyFormItem',
          props: {
            label: 'Name',
            prop: 'name',
          },
          children: [
            {
              componentName: 'TinyInput',
              props: {
                modelValue: {
                  type: 'JSExpression',
                  model: true,
                  value: 'this.state.formData.name',
                },
              },
            },
          ],
        },
        {
          componentName: 'TinyFormItem',
          props: {
            label: 'Age',
            prop: 'age',
          },
          children: [
            {
              componentName: 'TinyInput',
              props: {
                modelValue: {
                  type: 'JSExpression',
                  model: true,
                  value: 'this.state.formData.age',
                },
              },
            },
          ],
        },
      ],
    },
    {
      componentName: 'TinyButton',
      props: {
        text: 'View State',
        onClick: {
          type: 'JSFunction',
          value: "function() { this.callAction('getState'); }",
        },
      },
    },
  ],
});

// State restored from history (merged into global state on initialization)
const historyState = {
  formData: {
    name: 'John Doe',
    age: 30,
  },
};

const customActions = {
  getState: {
    execute: (params: any, context: Record<string, any>) => {
      const state = context.state;
      alert(`History State:\n${JSON.stringify(state, null, 2)}`);
    },
  },
};
</script>
