// packages/frameworks/vue/src/renderer/SchemaCardRenderer.vue
<script setup lang="ts">
import { ref, watch, computed, inject, nextTick, onErrorCaptured, provide } from 'vue';
// @ts-ignore
import defaultSchemaRenderer, { RENDERER_SETTINGS_KEY } from '@opentiny/tiny-schema-renderer';
import { DeltaPatcher, repairJson, RepairJsonState } from '@opentiny/genui-sdk-core';
import { requiredCompleteFieldSelectors as internalRequiredCompleteFieldSelectors } from './config';
import { GENUI_RENDERER, GENUI_MATERIALS, type GenuiMaterials } from '../chat/injection-tokens';
import type { IRendererProps } from './renderer.types';
import { cardIdSymbol } from '../chat/useChat';
import { useI18n } from '../chat/i18n';

onErrorCaptured((error) => {
  console.error('GenuiRenderer error:', error);
  return true;
});

const props = withDefaults(defineProps<IRendererProps>(), {
  isJsonComplete: true,
});

const schema = ref<any>({});
const rendererInstance = ref<defaultSchemaRenderer>(null);

const callAction = (actionName: string, params: any) => {
  if (!props.customActions?.[actionName]) {
    console.warn(`Action ${actionName} not found`);
    return;
  }
  return props.customActions[actionName]?.execute(params, rendererInstance.value.getContext());
};

const SchemaRenderer = inject(GENUI_RENDERER, defaultSchemaRenderer);
const vueMaterials = inject<GenuiMaterials>(GENUI_MATERIALS, {});
const customSettings = inject(RENDERER_SETTINGS_KEY, {});

provide(RENDERER_SETTINGS_KEY, {
  ...customSettings,
  materials: {
    ...vueMaterials,
    ...props.customComponents,
  },
});

const deltaPatcher = new DeltaPatcher({
  requiredCompleteFieldSelectors: [
    ...internalRequiredCompleteFieldSelectors,
    ...(props.requiredCompleteFieldSelectors || []),
  ],
});

const { t } = useI18n();

const errorSchema = {
  componentName: 'Page',
  children: [
    {
      componentName: 'Text',
      props: {
        text: t('renderer.error.displayError'),
        style: 'line-height: 40px; color: var(--tv-color-error-text)',
      },
    },
  ],
};

const isError = ref(false);

const displaySchema = computed(() => {
  if (isError.value) {
    return errorSchema;
  }
  return schema.value;
});

let updateActionTimer: any | null = null;

function updateContextAndState() {
  rendererInstance.value?.setContext({
    callAction,
  });
  rendererInstance.value?.setContext({
    [cardIdSymbol]: props.id,
  });
  rendererInstance.value?.setState(props.state || {});
}

watch(
  () => props.customActions,
  () => {
    nextTick(() => updateContextAndState());
  },
  { deep: true },
);

watch(
  [() => props.content, () => props.isJsonComplete, () => props.generating],
  ([newVal, isJsonComplete]) => {
    isError.value = false;
    let json: any = newVal;
    let isCompleted = true;
    if (typeof newVal === 'string') {
      if (newVal.trim()) {
        const { value, state } = repairJson(newVal);
        if (!value || typeof value !== 'object') {
          isError.value = true;
          return;
        }
        json = value;
        isCompleted = state === RepairJsonState.SUCCESS;
      } else {
        json = {};
      }
    } else {
      isCompleted = props.generating ? false : (isJsonComplete ?? true);
    }
    if (!isCompleted && json && 'lifeCycles' in json) {
      const { lifeCycles, ...rest } = json;
      json = rest;
    }
    deltaPatcher.patchWithDelta(schema.value, json, isCompleted); // TODO： 速率限制
    if (!updateActionTimer) {
      updateActionTimer = nextTick(() => {
        if (!rendererInstance.value) return;
        updateContextAndState();
        updateActionTimer = null;
      });
    }
  },
  {
    immediate: true,
  },
);
// 异步组件可能在更新context时候并未ready，导致恢复会话的时候context没更新
watch(
  () => rendererInstance.value,
  (newVal) => {
    if (newVal && updateActionTimer) {
      nextTick(() => updateContextAndState());
      updateActionTimer = null;
    }
  },
  {
    immediate: true,
  },
);
</script>

<template>
  <div class="schema-render-container">
    <slot name="header" :schema="schema" :isError="isError" :isFinished="!props.generating"></slot>
    <SchemaRenderer
      :schema="displaySchema"
      :generating="props.generating"
      :is-json-complete="props.generating ? false : (props.isJsonComplete ?? true)"
      :custom-actions="props.customActions"
      :renderer-id="props.id"
      :renderer-state="props.state"
      ref="rendererInstance"
    />
    <slot name="footer" :schema="schema" :isError="isError" :isFinished="!props.generating"></slot>
  </div>
</template>

<style scoped>
@import url('./custom.css');

.schema-render-container {
  position: relative;
  color: var(--tv-color-text, #191919);
}

.schema-render-container:has(.loading-warp):after {
  display: none;
}

:deep(.loading-warp.loading-warp) {
  display: none;
}

:deep(.loading-warp .loading) {
  display: none;
}
</style>

// packages/frameworks/react/src/renderer/SchemaCardRenderer.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  useContext,
} from 'react';
import { DeltaPatcher, repairJson, RepairJsonState } from '@opentiny/genui-sdk-core';
import type { RootNode } from '@opentiny/genui-sdk-core';
import { SchemaRenderer } from '@opentiny/tiny-schema-renderer-react';
import { PageContextProvider } from '@opentiny/tiny-schema-renderer-react';
import type { SchemaRendererHandle } from '@opentiny/tiny-schema-renderer-react';
import { RendererContext } from './RendererContext';
import { useGenuiMaterials } from '../config-provider';
import { requiredCompleteFieldSelectors as defaultSelectors } from './config';
import type { IRendererProps } from './renderer.types';

const errorSchema: RootNode = {
  componentName: 'Page',
  children: [
    {
      componentName: 'Text',
      props: { text: 'Schema rendering error', style: 'line-height: 40px; color: #c00' },
    },
  ],
};

const emptySchema: RootNode = { componentName: 'Page', children: [] };

/**
 * 流式卡片渲染器：repairJson + DeltaPatcher，将 content 转为 schema 后交给基础渲染器。
 * 对齐 Vue 的 SchemaCardRenderer.vue + inject(GENUI_RENDERER) 模式：
 * 通过 RendererContext 注入基础渲染器，默认使用 @opentiny/tiny-schema-renderer-react。
 */
export const SchemaCardRenderer = forwardRef<SchemaRendererHandle, IRendererProps>(
  function SchemaCardRenderer(props, ref) {
    // 通过 Context 注入基础渲染器，对齐 Vue 的 inject(GENUI_RENDERER, defaultSchemaRenderer)
    const BaseRenderer = useContext(RendererContext) ?? SchemaRenderer;
    // 对齐 Vue provide(RENDERER_SETTINGS_KEY, { materials: { ...vueMaterials, ...customComponents } })
    const contextMaterials = useGenuiMaterials();
    const mergedMaterials = useMemo(
      () => ({ ...contextMaterials, ...props.customComponents }),
      [contextMaterials, props.customComponents],
    );
    const rendererRef = useRef<SchemaRendererHandle | null>(null);

    /**
     * 对齐 Vue SchemaCardRenderer.updateContextAndState：通过 ref 向基础渲染器注入流式属性。
     */
    const updateContextAndState = useCallback(() => {
      const instance = rendererRef.current;
      if (!instance) return;

      instance.setContext({
        callAction: (actionName: string, params?: unknown) => {
          if (!props.customActions?.[actionName]) {
            console.warn(`Action ${actionName} not found`);
            return;
          }
          return props.customActions[actionName].execute(params, instance.getContext());
        },
      });
      if (props.id) {
        instance.setContext({ cardId: props.id });
      }
      instance.setState(props.state || {});
    }, [props.customActions, props.id, props.state]);

    const setRendererRef = useCallback(
      (instance: SchemaRendererHandle | null) => {
        rendererRef.current = instance;
        if (typeof ref === 'function') {
          ref(instance);
        } else if (ref) {
          ref.current = instance;
        }
        if (instance) {
          updateContextAndState();
        }
      },
      [ref, updateContextAndState],
    );

    useEffect(() => {
      updateContextAndState();
    }, [updateContextAndState]);

    const schemaRef = useRef<RootNode>({ ...emptySchema });
    const [displaySchema, setDisplaySchema] = useState<RootNode>(schemaRef.current);
    const [isError, setIsError] = useState(false);
    const patcherRef = useRef(
      new DeltaPatcher({
        requiredCompleteFieldSelectors: [
          ...defaultSelectors,
          ...(props.requiredCompleteFieldSelectors || []),
        ],
      }),
    );

    const contentKeyRef = useRef('');
    useEffect(() => {
      setIsError(false);
      let json: Record<string, unknown> = {};
      let isCompleted = true;
      const raw = props.content;

      if (typeof raw === 'string') {
        if (raw.trim()) {
          const { value, state } = repairJson(raw);
          if (!value || typeof value !== 'object') {
            setIsError(true);
            return;
          }
          json = value as Record<string, unknown>;
          isCompleted = state === RepairJsonState.SUCCESS;
        }
      } else {
        json = (raw as Record<string, unknown>) || {};
        isCompleted = props.generating ? false : (props.isJsonComplete ?? true);
      }

      if (!isCompleted && json && 'lifeCycles' in json) {
        const { lifeCycles: _, ...rest } = json;
        json = rest;
      }

      const nextKey = JSON.stringify(json) + String(isCompleted);
      if (!props.generating && contentKeyRef.current === nextKey) return;
      contentKeyRef.current = nextKey;

      patcherRef.current.patchWithDelta(schemaRef.current, json, isCompleted);
      setDisplaySchema({ ...schemaRef.current });
    }, [props.content, props.isJsonComplete, props.generating]);

    return (
      <PageContextProvider
        settings={{ materials: mergedMaterials }}
        customActions={props.customActions}
      >
        <div className="genui-renderer-container schema-render-container">
          <BaseRenderer
            ref={setRendererRef}
            schema={isError ? errorSchema : displaySchema}
          />
        </div>
      </PageContextProvider>
    );
  },
);
